### login user
POST http://localhost:8080/users/auth
Content-Type: application/json

{
  "email": "asd@gmail.com",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token) %}

### create room
POST http://localhost:8080/rooms
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "users": [1,9]
}

### add message
POST http://localhost:8080/rooms/message/cf9829a26524a6c820df2b8d0a7716d9b22f0be3a6d2a80836e8ac72b0417e67
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "text": "hi8"
}

### get room with messages
GET http://localhost:8080/rooms/get/22
Authorization: Bearer {{auth_token}}

###test
GET http://localhost:8080/rooms/test

