### login user
POST http://localhost:8080/users/auth
Content-Type: application/json

{
  "email": "asd@gmail.com",
  "password": "12345678"
}

### create user
POST http://localhost:8080/users/
Content-Type: application/json

{
  "email": "bebo@gmail.com",
  "password": "12345678",
  "gender": "male",
  "phone": "01272567081",
  "name": "bebo"

}